"""
Name: Gabrielle Vays and Analia Castellanos
Date: (11/04/2025)
Assignment: Assignment #4
Due Date: November 4th

About this project: This project implements a multithreaded Internet Chat Server that allows multiple
clients to connect, register, and communicate through various chat commands.
Users can register or log in, start or join chat rooms, send private or public messages,
view online users, set personal information, and manage user interactions through
blocking and unblocking. The server handles multiple concurrent clients using threads
and ensures safe access to shared data through locks.

Example Tests:
All passed.

Assumptions: 
• Input is well-formed (valid commands, proper argument count, etc.).
• Usernames are unique and case-insensitive.
• The server and clients are run on the same linprog network.
• To run this program:
    1. Start the server using:  python3 Castellanos_A_Vays_G_assignment4.py <server_port>
       (Example: python3 Castellanos_A_Vays_G_assignment4.py 55555)
    2. In a separate terminal, connect using:  telnet linprog <server_port>
       (Example: telnet linprog 55555)
• Clients connect via telnet or a similar socket-based client.
• The server runs continuously and gracefully handles multiple users joining and leaving.
All work below was performed solely by (Gabrielle Vays and Analia Castellanos).
I did not use code generated by an AI tool.
"""

from socket import *
import sys
import threading
import os
from dataclasses import dataclass, field
from threading import RLock

GOODBYEMSGFILE = "./goodbye.txt"
BEFORELOGINMSGFILE = "./prelogin.txt"
USERS_FILE = "./users.txt"
BLOCKED_FILE = "./blocked.txt"

beforeLoginMsg = ''
goodbyeMsg = ''

users = {} #{ username: password }
user_info = {}  # {username: info_text}
blocked_users = {}  # { username: set_of_blocked_usernames }
def canon(u: str) -> str:
    return u.strip().lower()

# ---------------------- ROOM MANAGEMENT ----------------------

@dataclass
class Room:
    id: int
    topic: str
    leader: str
    members: set[str] = field(default_factory=set)

class State:
    def __init__(self):
        self._lock = RLock()
        self.rooms: dict[int, Room] = {}
        self.online_users: dict[str, socket] = {}
        self._next_room_id = 1

    def new_room(self, topic: str, leader: str) -> int:
        with self._lock:
            rid = self._next_room_id
            self._next_room_id += 1
            self.rooms[rid] = Room(rid, topic, leader, {leader})
            return rid

    def list_rooms(self):
        with self._lock:
            return [
                f"{rid}: {r.topic} | leader={r.leader} | members={len(r.members)}"
                for rid, r in sorted(self.rooms.items())
            ]

    def join_room(self, rid: int, user: str):
        with self._lock:
            if rid not in self.rooms:
                return False
            self.rooms[rid].members.add(user)
            return True

    def leave_room(self, rid: int, user: str):
        with self._lock:
            if rid not in self.rooms:
                return None
            r = self.rooms[rid]
            if user not in r.members:
                return None
            r.members.remove(user)
            leader_left = (user == r.leader)
            if leader_left:
                members = r.members.copy()
                del self.rooms[rid]
                return members
            return set()

    def broadcast_to_room(self, rid: int, sender: str, msg: str):
        with self._lock:
            room = self.rooms.get(rid)
            if not room:
                return False
            full_msg = f"[{rid}] {sender}: {msg}"
            for member in room.members:
                if member == sender:
                    continue
                # skip if receiver has blocked sender
                if canon(sender) in blocked_users.get(canon(member), set()):
                    continue
                member_sock = self.online_users.get(member)
                if member_sock:
                    safe_send_line(member_sock, full_msg)
                    safe_send_line(member_sock, f"<{member}:> ")
                else:
                    print(f"[DEBUG] no socket found for {member}")
        return True

STATE = State()

def loadMsgs():
    global beforeLoginMsg
    global goodbyeMsg
    
    with open(BEFORELOGINMSGFILE, "r") as f:
        beforeLoginMsg = f.read()
    with open(GOODBYEMSGFILE, "r") as f:
        goodbyeMsg = f.read()

#-----established users-----
def load_users():
    global users
    if not os.path.exists(USERS_FILE):
        open(USERS_FILE, "w").close()
    with open(USERS_FILE, "r") as f:
        for line in f:
            parts = line.strip().split(":")
            if len(parts) == 2:
                users[parts[0]] = parts[1]

def save_users():
    with open(USERS_FILE, "w") as f:
        for u, p in users.items():
            f.write(f"{u}:{p}\n")

def load_blocked():
    """Load persistent block lists from BLOCKED_FILE into blocked_users."""
    global blocked_users
    if not os.path.exists(BLOCKED_FILE):
        open(BLOCKED_FILE, "w").close()
    with open(BLOCKED_FILE, "r") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = line.split(":")
            if len(parts) != 2:
                continue
            owner, csv = parts
            owner_c = canon(owner)
            if csv:
                blocked_users[owner_c] = set(canon(x) for x in csv.split(",") if x)
            else:
                blocked_users[owner_c] = set()

def save_blocked():
    """Persist blocked_users to BLOCKED_FILE."""
    with open(BLOCKED_FILE, "w") as f:
        for owner_c, blocked_set in blocked_users.items():
            # store display-friendly names; we keep canonical in memory
            csv = ",".join(sorted(blocked_set))
            f.write(f"{owner_c}:{csv}\n")
                
def handle_room_cmd(sock, user, command, args):
    # CREATE ROOM
    if command == "start":
        if not args:
            mySendAll(sock, b"Usage: start <topic>\n")
            return
        topic = " ".join(args)
        rid = STATE.new_room(topic, user)
        mySendAll(sock, f"Room {rid} created for topic '{topic}'\n".encode())
        return

    # LIST ROOMS
    if command == "rooms":
        rooms = STATE.list_rooms()
        if not rooms:
            mySendAll(sock, b"(no rooms)\n")
        else:
            for line in rooms:
                mySendAll(sock, f"{line}\n".encode())
        return

    # JOIN ROOM
    if command == "join":
        if len(args) != 1 or not args[0].isdigit():
            mySendAll(sock, b"Usage: join <room#>\n")
            return
        rid = int(args[0])
        if not STATE.join_room(rid, user):
            mySendAll(sock, b"Room not found.\n")
        else:
            mySendAll(sock, f"Joined room {rid}\n".encode())
        return

    # LEAVE ROOM
    if command == "leave":
        if len(args) != 1 or not args[0].isdigit():
            mySendAll(sock, b"Usage: leave <room#>\n")
            return
        rid = int(args[0])
        result = STATE.leave_room(rid, user)
        if result is None:
            mySendAll(sock, b"Room not found or not a member.\n")
        elif result:  # leader left -> result is remaining members
            notify_room_closed(rid, result, "leader left")
            mySendAll(sock, f"You (leader) closed room {rid}\n".encode())
        else:
            mySendAll(sock, f"You left room {rid}\n".encode())
        return

    # SAY MESSAGE
    if command == "say":
        if len(args) < 2 or not args[0].isdigit():
            mySendAll(sock, b"Usage: say <room#> <msg>\n")
            return
        rid = int(args[0])
        msg = " ".join(args[1:])

        # validate room and membership
        r = STATE.rooms.get(rid)
        if not r:
            mySendAll(sock, b"Room not found.\n")
            return
        if user not in r.members:
            mySendAll(sock, b"Not a member of that room.\n")
            return

        # broadcast (respects blocks)
        if STATE.broadcast_to_room(rid, user, msg):
            mySendAll(sock, b"Message sent.\n")
        else:
            mySendAll(sock, b"Failed to deliver message.\n")
        return
    
"""
Send all data to sock, return 1 if successful
-1 if failed (socket error)
"""
def mySendAll(sock, data):
    total_sent = 0
    data_length = len(data)

    try:
        while total_sent < data_length:
            sent = sock.send(data[total_sent:])
            if sent == 0:
                # Socket connection broken
                return -1
            total_sent += sent

    except Exception :
        print("Socket send error in mySendAll.\n")
        return -1

    return 1

def safe_send_line(sock, line: str):
    """Send a single line to a socket safely."""
    try:
        sock.sendall((line.rstrip() + "\n").encode())
    except Exception as e:
        print(f"Send error: {e}")

def notify_room_closed(rid: int, members: set[str], reason: str):
    """Notify remaining members that a room closed for a reason."""
    with STATE._lock:
        for m in members:
            msock = STATE.online_users.get(m)
            if msock:
                safe_send_line(msock, f"[room {rid}] closed ({reason})")
                safe_send_line(msock, f"<{m}:> ")       

def processCmd(userName, sock, cmd):
    parts = cmd.strip().split()
    if not parts:
        return
    command = parts[0].lower()
    args = parts[1:]

    if command == "help":
        help_text = (
            "Available commands:\n"
            "who - list online users\n"
            "status [user] - show user info\n"
            "info [text] - set or show your info\n"
            "start <topic> - create a room\n"
            "rooms - list rooms\n"
            "join <room#> - join a room\n"
            "leave <room#> - leave a room\n"
            "say <room#> <msg> - message room members\n"
            "shout <msg> - broadcast to all online\n"
            "tell <user> <msg> - send private message\n"
            "block/unblock <user> - mute/unmute a user\n"
            "quit / exit - log out\n"
            "help - show this message\n"
            "register <user> <passwd> - register a new user"
        )
        mySendAll(sock, help_text.encode())
        return

    if command == "who":
        with STATE._lock:
            if not STATE.online_users:
                mySendAll(sock, b"No users online.\n")
            else:
                for u in STATE.online_users:
                    mySendAll(sock, f"{u}\n".encode())
        return
    
    if command == "status":
        target = args[0] if args else userName
        info = user_info.get(target, "(no info)")
        if target in users:
            mySendAll(sock, f"{target}: {info}\n".encode())
        else:
            mySendAll(sock, b"User not found.\n")
        return
    
    if command == "info":
        if not args:
            info = user_info.get(userName, "(no info set)")
            mySendAll(sock, f"Your info: {info}\n".encode())
        else:
            user_info[userName] = " ".join(args)
            mySendAll(sock, b"Info updated.\n")
        return

    # --- ROOM COMMANDS ---
    if command in ("start", "rooms", "join", "leave", "say"):
        handle_room_cmd(sock, userName, command, args)
        return

    # ---- Message commands ------
    if command == "tell":
        if len(args) < 2:
            mySendAll(sock, b"Usage: tell <user> <message>\n")
            return

        target_raw = args[0]
        msg = " ".join(args[1:])

        sender_c = canon(userName)
        target_c = canon(target_raw)

        with STATE._lock:
            online_by_canon = {canon(u): s for (u, s) in STATE.online_users.items()}
            tsock = online_by_canon.get(target_c)

        if not tsock:
            mySendAll(sock, b"User not online.\n")
            return

        # If the receiver has blocked the sender, silently drop (or send a notice)
        if sender_c in blocked_users.get(target_c, set()):
            mySendAll(sock, b"Message sent.\n")  
            return

        safe_send_line(tsock, f"[private] {userName}: {msg}")
        mySendAll(sock, f"[to {target_raw}] {msg}\n".encode())
        return

    #----SHOUT-----
    if command == "shout":
        if len(args) < 1:
            mySendAll(sock, b"Usage: shout <message>\n")
            return

        msg = " ".join(args)
        full_msg = f"\n[shout] {userName}: {msg}\n"
        sender_c = canon(userName)

        with STATE._lock:
            for member, member_sock in STATE.online_users.items():
                if not member_sock:
                    continue

                #skip if blocked user
                blocked_set = blocked_users.get(canon(member), set())
                if sender_c in blocked_set:
                    print(f"[DEBUG] {member} has blocked {userName} - skipping")
                    continue

                safe_send_line(member_sock,f"\n{full_msg}\n<{member}:> ")
        mySendAll(sock, b"Message sent.\n")
        return
    
    #  BLOCK / UNBLOCK 
    if command == "block":
        if len(args) != 1:
            mySendAll(sock, b"Usage: block <user>\n")
            return
        owner = canon(userName)
        target = canon(args[0])
        blocked_users.setdefault(owner, set()).add(target)
        save_blocked()  # <-- ADD THIS
        mySendAll(sock, f"{args[0]} blocked.\n".encode())
        return

    if command == "unblock":
        if len(args) != 1:
            mySendAll(sock, b"Usage: unblock <user>\n")
            return
        owner = canon(userName)
        target = canon(args[0])
        s = blocked_users.get(owner, set())
        if target in s:
            s.remove(target)
            save_blocked()  # <-- ADD THIS
            mySendAll(sock, f"{args[0]} unblocked.\n".encode())
        else:
            mySendAll(sock, b"User was not blocked.\n")
        return

    # --- DEFAULT / OTHER COMMANDS ---
    if command == "quit" or command == "exit":
        mySendAll(sock, goodbyeMsg.encode())
        sock.close()
        return

    if command == "register":
        if len(args) != 2:
            mySendAll(sock, b"Usage: register <user> <passwd>\n")
            return
        new_user, new_pwd = args[0], args[1]

        #if already exists:
        if new_user in users:
            mySendAll(sock, f"Username '{new_user}' already exists.\n".encode())
            return

        #store user
        users[new_user] = new_pwd
        save_users()

        mySendAll(sock, f"Registered new user '{new_user}' successfully.\n".encode())
        return

    else:
        mySendAll(sock, f"Server response to '{cmd}'\n".encode())

def handleOneClient(sock):

    mySendAll(sock, beforeLoginMsg.encode())
    mySendAll(sock, "Type 'guest', 'login', or 'register': ".encode())
    choice = sock.recv(1000).decode().strip().lower()

    userName = None
    isGuest = False

    #for a guest login:
    if choice == "guest":
        userName = f"guest{len(users)+1}"
        isGuest = True
        with STATE._lock:
            STATE.online_users[userName] = sock
        print(f"[DEBUG] Added {userName} as guest to online users")
 
    #user registration:
    elif choice == "register":
        mySendAll(sock, "Enter new username: ".encode())
        uname = sock.recv(1000).decode().strip()
        if uname in users:
            mySendAll(sock, "Username already exists.\n".encode())
            sock.close()
            return
        #get password and save to dict
        mySendAll(sock, "Enter password: ".encode())
        pwd = sock.recv(1000).decode().strip()

        users[uname] = pwd
        save_users()
        userName = uname
        mySendAll(sock, f"Registered user '{uname}'\n".encode())
        with STATE._lock:
            STATE.online_users[userName] = sock
        print(f"[DEBUG] added {userName} to online users (registered)")

    #if user exists, login
    elif choice == "login":
        mySendAll(sock, "Username: ".encode())
        uname = sock.recv(1000).decode().strip()
        mySendAll(sock, "Password: ".encode())
        pwd = sock.recv(1000).decode().strip()
        if uname in users and users[uname] == pwd:
            userName = uname
            mySendAll(sock, f"Welcome back, {uname}!\n".encode())
            with STATE._lock:
                STATE.online_users[userName] = sock
            print(f"[DEBUG] added {userName} to online users (login)")
        else:
            mySendAll(sock, "Invalid login.\n".encode())
            sock.close()
            return

    else:
        mySendAll(sock, "Invalid option.\n".encode())
        sock.close()
        return

    welcome_banner = """ %%%%% """ 

    mySendAll(sock, welcome_banner.encode())
    if isGuest:
        mySendAll(sock, "You login as a guest. The only commands that you can use are 'register username password', 'exit', and 'quit'.\n".encode())
    else: 
        mySendAll(sock, f"You are logged in as {userName}.\n".encode())

    str = f"Welcome to the Internet Chat Room, {userName}!\n\n"
    mySendAll(sock, str.encode())

    cmdCount = 0
    mySendAll(sock, f"<{userName}:{cmdCount}> ".encode())

    #get chat commands in a loop
    while True:
        data = sock.recv(1000)
        if (len(data) == 0):
            print("Client closed connection")

            # --- Clean up any rooms the user was in ---
            for rid, r in list(STATE.rooms.items()):
                if userName in r.members:
                    if r.leader == userName:
                        members = STATE.leave_room(rid, userName)
                        notify_room_closed(rid, members, "leader disconnected")
                    else:
                        r.members.remove(userName)

            with STATE._lock:
                STATE.online_users.pop(userName, None)

            sock.close()
            break

        cmd = data.decode().strip()
        command = cmd.split()[0].lower()

        #exit/quit if told by command
        if (command == 'quit' or command == 'exit'):
            # --- Clean up rooms on quit ---
            for rid, r in list(STATE.rooms.items()):
                if userName in r.members:
                    if r.leader == userName:
                        members = STATE.leave_room(rid, userName)
                        notify_room_closed(rid, members, "leader left")
                    else:
                        r.members.remove(userName)

            mySendAll(sock, goodbyeMsg.encode())
            with STATE._lock:
                STATE.online_users.pop(userName, None)
            print(f"[DEBUG] removed {userName} from online users")
            sock.close()
            break
        #else use processCmd() for all other commands
        else: 
            processCmd(userName, sock, cmd)

        # send prompt
        cmdCount = cmdCount + 1
        mySendAll(sock, f"<{userName}:{cmdCount}> ".encode())


#--main server ---
if len(sys.argv) != 2:
    print("Usage: server_port")
    sys.exit(1)

loadMsgs()
load_users()
load_blocked()

#create socket and allow port usage
s = socket()
s.setsockopt(SOL_SOCKET, SO_REUSEADDR, 1)

h = gethostname()
#print(sys.argv[0], sys.argv[1])

#bind to h on the chosen port
s.bind((h, int(sys.argv[1])))
s.listen(5)

print(sys.argv[0], sys.argv[1])

while True:
    sock, addr = s.accept()
    print("Receive client connection from ", addr)
    p = threading.Thread(target=handleOneClient, args=(sock,), daemon = True)
    p.start()
    
