"""
Name: Gabrielle Vays and Analia Castellanos
Date: (The Date)
Assignment: Assignment #4
Due Date: November 4th
About this project: (write a small blurb about what this project's goals are/what tasks it accomplishes)
Assumptions: (write any assumptions made here (ex: assumes correct user input))
All work below was performed solely by (Your Name).
I did not use code generated by an AI tool.
"""

from socket import *
import sys
import threading
import os
from dataclasses import dataclass, field
from threading import RLock

GOODBYEMSGFILE = "./goodbye.txt"
BEFORELOGINMSGFILE = "./prelogin.txt"
USERS_FILE = "./users.txt"

beforeLoginMsg = ''
goodbyeMsg = ''

users = {} #{ username: password }

# ---------------------- ROOM MANAGEMENT ----------------------

@dataclass
class Room:
    id: int
    topic: str
    leader: str
    members: set[str] = field(default_factory=set)

class State:
    def __init__(self):
        self._lock = RLock()
        self.rooms: dict[int, Room] = {}
        self.online_users: dict[str, socket] = {}
        self._next_room_id = 1

    def new_room(self, topic: str, leader: str) -> int:
        with self._lock:
            rid = self._next_room_id
            self._next_room_id += 1
            self.rooms[rid] = Room(rid, topic, leader, {leader})
            return rid

    def list_rooms(self):
        with self._lock:
            return [
                f"{rid}: {r.topic} | leader={r.leader} | members={len(r.members)}"
                for rid, r in sorted(self.rooms.items())
            ]

    def join_room(self, rid: int, user: str):
        with self._lock:
            if rid not in self.rooms:
                return False
            self.rooms[rid].members.add(user)
            return True

    def leave_room(self, rid: int, user: str):
        with self._lock:
            if rid not in self.rooms:
                return None
            r = self.rooms[rid]
            if user not in r.members:
                return None
            r.members.remove(user)
            leader_left = (user == r.leader)
            if leader_left:
                members = r.members.copy()
                del self.rooms[rid]
                return members
            return set()

    def broadcast_to_room(self, rid: int, sender: str, msg: str):
        with self._lock:
            room = self.rooms.get(rid)
            if not room:
                return False

            #prepare the message string
            full_msg = f"\n[{rid}] {sender}: {msg}\n"
            for member in room.members:
                if member == sender:
                    continue
                member_sock = self.online_users.get(member)
                if member_sock:
                    safe_send_line(member_sock, full_msg)
                    safe_send_line(member_sock, f"<{member}:> ")
                else:
                    print(f"[DEBUG] no socket found for {member}")
        return True

STATE = State()

def loadMsgs():
    global beforeLoginMsg
    global goodbyeMsg
    
    with open(BEFORELOGINMSGFILE, "r") as f:
        beforeLoginMsg = f.read()
    with open(GOODBYEMSGFILE, "r") as f:
        goodbyeMsg = f.read()

#-----established users-----
def load_users():
    global users
    if not os.path.exists(USERS_FILE):
        open(USERS_FILE, "w").close()
    with open(USERS_FILE, "r") as f:
        for line in f:
            parts = line.strip().split(":")
            if len(parts) == 2:
                users[parts[0]] = parts[1]

def save_users():
    with open(USERS_FILE, "w") as f:
        for u, p in users.items():
            f.write(f"{u}:{p}\n")
                
def handle_room_cmd(sock, user, command, args):
    # CREATE ROOM
    if command == "start":
        if not args:
            mySendAll(sock, b"Usage: start <topic>\n")
            return
        topic = " ".join(args)
        rid = STATE.new_room(topic, user)
        mySendAll(sock, f"Room {rid} created for topic '{topic}'\n".encode())
        return

    # LIST ROOMS
    if command == "rooms":
        rooms = STATE.list_rooms()
        if not rooms:
            mySendAll(sock, b"(no rooms)\n")
        else:
            for line in rooms:
                mySendAll(sock, f"{line}\n".encode())
        return

    # JOIN ROOM
    if command == "join":
        if len(args) != 1 or not args[0].isdigit():
            mySendAll(sock, b"Usage: join <room#>\n")
            return
        rid = int(args[0])
        if not STATE.join_room(rid, user):
            mySendAll(sock, b"Room not found.\n")
        else:
            mySendAll(sock, f"Joined room {rid}\n".encode())
        return

    # LEAVE ROOM
    if command == "leave":
        if len(args) != 1 or not args[0].isdigit():
            mySendAll(sock, b"Usage: leave <room#>\n")
            return
        rid = int(args[0])
        result = STATE.leave_room(rid, user)
        if result is None:
            mySendAll(sock, b"Room not found or not a member.\n")
        elif result:  # leader left
            for m in result:
                mySendAll(sock, f"[room {rid}] closed (leader left)\n".encode())
            mySendAll(sock, f"You (leader) closed room {rid}\n".encode())
        else:
            mySendAll(sock, f"You left room {rid}\n".encode())
        return

    # SAY MESSAGE
    if command == "say":
        if len(args) < 2 or not args[0].isdigit():
            mySendAll(sock, b"Usage: say <room#> <msg>\n")
            return
        rid = int(args[0])
        msg = " ".join(args[1:])

        #make sure there is safe thread accessing with lock
        with STATE._lock:
            r = STATE.rooms.get(rid)
            if not r:
                mySendAll(sock, b"Room not found.\n")
                return
            if user not in r.members:
                mySendAll(sock, b"Not a member of that room.\n")
                return

        # Find the socket by username
        # (simplest approach: message everyone in same thread pool)
        if STATE.broadcast_to_room(rid, user, msg):
            mySendAll(sock, b"Message sent.\n")
        else:
            mySendAll(sock, b"Failed to deliver message.\n")
        return
    
"""
Send all data to sock, return 1 if successful
-1 if failed (socket error)
"""
def mySendAll(sock, data):
    total_sent = 0
    data_length = len(data)

    try:
        while total_sent < data_length:
            sent = sock.send(data[total_sent:])
            if sent == 0:
                # Socket connection broken
                return -1
            total_sent += sent

    except Exception :
        print("Socket send error in mySendAll.\n")
        return -1

    return 1

def safe_send_line(sock, line: str):
    """Send a single line to a socket safely."""
    try:
        sock.sendall((line.rstrip() + "\n").encode())
    except Exception as e:
        print(f"Send error: {e}")

def processCmd(userName, sock, cmd):
    parts = cmd.strip().split()
    if not parts:
        return
    command = parts[0].lower()
    args = parts[1:]

    # --- ROOM COMMANDS ---
    if command in ("start", "rooms", "join", "leave", "say"):
        handle_room_cmd(sock, userName, command, args)
        return

    # ---- Message commands ------
    if command == "tell":
        if len(args) < 2:
            mySendAll(sock, b"Usage: tell <user> <message>\n")
            return

        target_user = args[0]
        msg = " ".join(args[1:])

        with STATE._lock:
            target_sock = STATE.online_users.get(target_user)
        
        if not target_sock:
            mySendAll(sock, f"User '{target_user}' not found or offline.\n".encode())
            return

        #send to the recipient
        safe_send_line(target_sock, f"[private] {userName}: {msg}\n<{target_user}:> ")
        #confirm to sender
        mySendAll(sock, f"[to {target_user}] {msg}\n".encode())
        return

    if command == "shout":
        if len(args) < 1:
            mySendAll(sock, b"Usage: shout <message>\n")
            return

        msg = " ".join(args)
        full_msg = f"\n[shout] {userName}: {msg}\n"

        with STATE._lock:
            for member, member_sock in STATE.online_users.items():
                #send to everyone including sender
                if member_sock:
                    safe_send_line(member_sock, full_msg)
                    safe_send_line(member_sock, f"<{member}:> ")
        return

    # --- DEFAULT / OTHER COMMANDS ---
    if command == "quit" or command == "exit":
        mySendAll(sock, goodbyeMsg.encode())
        sock.close()
        return
    else:
        mySendAll(sock, f"Server response to '{cmd}'\n".encode())

def handleOneClient(sock):

    mySendAll(sock, beforeLoginMsg.encode())
    mySendAll(sock, "Type 'guest', 'login', or 'register': ".encode())
    choice = sock.recv(1000).decode().strip().lower()

    userName = None
    isGuest = False

    #for a guest login:
    if choice == "guest":
        userName = f"guest{len(users)+1}"
        isGuest = True
        with STATE._lock:
            STATE.online_users[userName] = sock
        print(f"[DEBUG] Added {userName} as guest to online users")
 
    #user registration:
    elif choice == "register":
        mySendAll(sock, "Enter new username: ".encode())
        uname = sock.recv(1000).decode().strip()
        if uname in users:
            mySendAll(sock, "Username already exists.\n".encode())
            sock.close()
            return
        #get password and save to dict
        mySendAll(sock, "Enter password: ".encode())
        pwd = sock.recv(1000).decode().strip()

        users[uname] = pwd
        save_users()
        userName = uname
        mySendAll(sock, f"Registered user '{uname}'\n".encode())
        with STATE._lock:
            STATE.online_users[userName] = sock
        print(f"[DEBUG] added {userName} to online users (registered)")

    #if user exists, login
    elif choice == "login":
        mySendAll(sock, "Username: ".encode())
        uname = sock.recv(1000).decode().strip()
        mySendAll(sock, "Password: ".encode())
        pwd = sock.recv(1000).decode().strip()
        if uname in users and users[uname] == pwd:
            userName = uname
            mySendAll(sock, f"Welcome back, {uname}!\n".encode())
            with STATE._lock:
                STATE.online_users[userName] = sock
            print(f"[DEBUG] added {userName} to online users (login)")
        else:
            mySendAll(sock, "Invalid login.\n".encode())
            sock.close()
            return

    else:
        mySendAll(sock, "Invalid option.\n".encode())
        sock.close()
        return

    welcome_banner = """ %%%%% """ #change to actual banner

    mySendAll(sock, welcome_banner.encode())
    if isGuest:
        mySendAll(sock, "You login as a guest. The only commands that you can use are 'register username password', 'exit', and 'quit'.\n".encode())
    else: 
        mySendAll(sock, f"You are logged in as {userName}.\n".encode())

    str = f"Welcome to the Internet Chat Room, {userName}!\n\n"
    mySendAll(sock, str.encode())

    cmdCount = 0
    mySendAll(sock, f"<{userName}:{cmdCount}> ".encode())

    #get chat commands in a loop
    while True:
        data = sock.recv(1000)
        if (len(data) == 0):
            print("Client closed connection")

    # --- Clean up any rooms the user was in ---
            for rid, r in list(STATE.rooms.items()):
                if userName in r.members:
                    if r.leader == userName:
                        members = STATE.leave_room(rid, userName)
                        # notify remaining members that leader left
                        for m in members:
                            mySendAll(sock, f"[room {rid}] closed (leader disconnected)\n".encode())
                    else:
                        r.members.remove(userName)

            sock.close()
            break

        cmd = data.decode().strip()
        command = cmd.split()[0].lower()

        #exit/quit if told by command
        if (command == 'quit' or command == 'exit'):
            # --- Clean up rooms on quit ---
            for rid, r in list(STATE.rooms.items()):
                if userName in r.members:
                    if r.leader == userName:
                        members = STATE.leave_room(rid, userName)
                        for m in members:
                            mySendAll(sock, f"[room {rid}] closed (leader left)\n".encode())
                    else:
                        r.members.remove(userName)

            mySendAll(sock, goodbyeMsg.encode())
            with STATE._lock:
                STATE.online_users.pop(userName, None)
            print(f"[DEBUG] removed {userName} from online users")
            sock.close()
            break
        #else use processCmd() for all other commands
        else: 
            processCmd(userName, sock, cmd)

        # send prompt
        cmdCount = cmdCount + 1
        mySendAll(sock, f"<{userName}:{cmdCount}> ".encode())


#--main server ---
if len(sys.argv) != 2:
    print("Usage: server_port")
    sys.exit(1)

loadMsgs()
load_users()

#create socket and allow port usage
s = socket()
s.setsockopt(SOL_SOCKET, SO_REUSEADDR, 1)

h = gethostname()
#print(sys.argv[0], sys.argv[1])

#bind to h on the chosen port
s.bind((h, int(sys.argv[1])))
s.listen(5)

print(sys.argv[0], sys.argv[1])

while True:
    sock, addr = s.accept()
    print("Receive client connection from ", addr)
    p = threading.Thread(target=handleOneClient, args=(sock,), daemon = True)
    p.start()
    
